/var/log/hp-wmi-omen-verify.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    create 644 root root
}

/var/log/hp-wmi-omen-dkms.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
    create 644 root root
}